 
   - name: New user name devops
     user:
          name={{username}}
          password={{ devops_password }}
 
   - name: Giving Admin permissions to user, devops
     copy:
          dest: "/etc/sudoers.d/{{username}}"
          content: "{{username}}  ALL=(ALL)  NOPASSWD: ALL"
 
   - name: SSH Key
     authorized_key: user={{username}}
                     key="{{ lookup('file', 'id_rsa.pub') }}"
                     state=present
                     
   - name: Disabling Password Authentication
     lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PasswordAuthentication'
           line="PasswordAuthentication no"
           state=present
           backup=yes

   - name: Disabling Root Login
     lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin no"
           state=present
           backup=yes
           
     notify:
        - restart ssh
