# This file helps you get started

name: CI

# Controls when the workflow will run
on:
  # To trigger the workflow on push or pull requests
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # To run the workflow manually
  workflow_dispatch:

# Sequential or in parallel Jobs
jobs:
  # "build Job"
  build:
    # Job runs on Ubuntu (latest OS)
    runs-on: ubuntu-latest

    # Sequence of tasks to execute the job
    steps:
      # Action Checkout 
      - uses: actions/checkout@v2

           
      - name: Copying files with the AWS CLI
        env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_DEFAULT_REGION: us-east-1
        run: |
         aws s3 sync . s3://devops_solutions-target --region us-east-1

      # Shell commands to run
      - name: Run shell script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
